/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'participantA' : UserId,
  'participantB' : UserId,
  'lastMessageAt' : Timestamp,
  'lastMessagePreview' : IDL.Text,
  'unreadA' : IDL.Nat,
  'unreadB' : IDL.Nat,
});
export const OnlineStatus = IDL.Variant({
  'away' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : UserId,
  'status' : OnlineStatus,
  'displayName' : IDL.Text,
  'lastSeen' : Timestamp,
  'avatar' : IDL.Opt(IDL.Text),
});
export const CallStatus = IDL.Variant({
  'ringing' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'ongoing' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallKind = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
export const CallRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'endedAt' : IDL.Opt(Timestamp),
  'kind' : CallKind,
  'conversationId' : IDL.Nat,
  'callee' : UserId,
  'caller' : UserId,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : IDL.Nat,
});
export const SignalKind = IDL.Variant({
  'iceCandidate' : IDL.Null,
  'offer' : IDL.Null,
  'answer' : IDL.Null,
});
export const SignalMessage = IDL.Record({
  'id' : IDL.Nat,
  'to' : UserId,
  'from' : UserId,
  'kind' : SignalKind,
  'sentAt' : Timestamp,
  'conversationId' : IDL.Nat,
  'payload' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptCall' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'declineCall' : IDL.Func([IDL.Nat], [], []),
  'endCall' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCalls' : IDL.Func([IDL.Nat], [IDL.Vec(CallRecord)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'listMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'markConversationRead' : IDL.Func([IDL.Nat], [], []),
  'pollSignals' : IDL.Func([IDL.Nat], [IDL.Vec(SignalMessage)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
  'sendSignal' : IDL.Func([IDL.Nat, UserId, SignalKind, IDL.Text], [], []),
  'startCall' : IDL.Func([IDL.Nat, CallKind], [IDL.Nat], []),
  'startConversation' : IDL.Func([UserId], [IDL.Nat], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Profile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'participantA' : UserId,
    'participantB' : UserId,
    'lastMessageAt' : Timestamp,
    'lastMessagePreview' : IDL.Text,
    'unreadA' : IDL.Nat,
    'unreadB' : IDL.Nat,
  });
  const OnlineStatus = IDL.Variant({
    'away' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : UserId,
    'status' : OnlineStatus,
    'displayName' : IDL.Text,
    'lastSeen' : Timestamp,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const CallStatus = IDL.Variant({
    'ringing' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'ongoing' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallKind = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const CallRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : CallStatus,
    'startedAt' : Timestamp,
    'endedAt' : IDL.Opt(Timestamp),
    'kind' : CallKind,
    'conversationId' : IDL.Nat,
    'callee' : UserId,
    'caller' : UserId,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'conversationId' : IDL.Nat,
  });
  const SignalKind = IDL.Variant({
    'iceCandidate' : IDL.Null,
    'offer' : IDL.Null,
    'answer' : IDL.Null,
  });
  const SignalMessage = IDL.Record({
    'id' : IDL.Nat,
    'to' : UserId,
    'from' : UserId,
    'kind' : SignalKind,
    'sentAt' : Timestamp,
    'conversationId' : IDL.Nat,
    'payload' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptCall' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'declineCall' : IDL.Func([IDL.Nat], [], []),
    'endCall' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCalls' : IDL.Func([IDL.Nat], [IDL.Vec(CallRecord)], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'listMessages' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'markConversationRead' : IDL.Func([IDL.Nat], [], []),
    'pollSignals' : IDL.Func([IDL.Nat], [IDL.Vec(SignalMessage)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [Message], []),
    'sendSignal' : IDL.Func([IDL.Nat, UserId, SignalKind, IDL.Text], [], []),
    'startCall' : IDL.Func([IDL.Nat, CallKind], [IDL.Nat], []),
    'startConversation' : IDL.Func([UserId], [IDL.Nat], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [Profile], []),
  });
};

export const init = ({ IDL }) => { return []; };