/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CallKind = { 'audio' : null } |
  { 'video' : null };
export interface CallRecord {
  'id' : bigint,
  'status' : CallStatus,
  'startedAt' : Timestamp,
  'endedAt' : [] | [Timestamp],
  'kind' : CallKind,
  'conversationId' : bigint,
  'callee' : UserId,
  'caller' : UserId,
}
export type CallStatus = { 'ringing' : null } |
  { 'missed' : null } |
  { 'ended' : null } |
  { 'ongoing' : null } |
  { 'declined' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Conversation {
  'id' : bigint,
  'participantA' : UserId,
  'participantB' : UserId,
  'lastMessageAt' : Timestamp,
  'lastMessagePreview' : string,
  'unreadA' : bigint,
  'unreadB' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Message {
  'id' : bigint,
  'body' : string,
  'read' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'conversationId' : bigint,
}
export type OnlineStatus = { 'away' : null } |
  { 'offline' : null } |
  { 'online' : null };
export interface Profile {
  'id' : UserId,
  'status' : OnlineStatus,
  'displayName' : string,
  'lastSeen' : Timestamp,
  'avatar' : [] | [string],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SignalKind = { 'iceCandidate' : null } |
  { 'offer' : null } |
  { 'answer' : null };
export interface SignalMessage {
  'id' : bigint,
  'to' : UserId,
  'from' : UserId,
  'kind' : SignalKind,
  'sentAt' : Timestamp,
  'conversationId' : bigint,
  'payload' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'acceptCall' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineCall' : ActorMethod<[bigint], undefined>,
  'endCall' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[bigint], [] | [Conversation]>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCalls' : ActorMethod<[bigint], Array<CallRecord>>,
  'listConversations' : ActorMethod<[], Array<Conversation>>,
  'listMessages' : ActorMethod<[bigint], Array<Message>>,
  'listUsers' : ActorMethod<[], Array<Profile>>,
  'markConversationRead' : ActorMethod<[bigint], undefined>,
  'pollSignals' : ActorMethod<[bigint], Array<SignalMessage>>,
  'schema' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[bigint, string], Message>,
  'sendSignal' : ActorMethod<[bigint, UserId, SignalKind, string], undefined>,
  'startCall' : ActorMethod<[bigint, CallKind], bigint>,
  'startConversation' : ActorMethod<[UserId], bigint>,
  'updateProfile' : ActorMethod<[string, [] | [string]], Profile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];